### ISSUE TITLE
Redesign reconciliation modal: Replace 4-tab system with progressive disclosure interface

### ISSUE THREAD

**Issue by daanvr** [MaastrichtU-Library/omekas-to-wikidata#15]
# Redesign Reconciliation Modal: Progressive Disclosure Interface

## Overview

Replace the current complex 4-tab reconciliation modal with a streamlined progressive disclosure design that dramatically improves user experience while maintaining all functionality. The current tab system creates cognitive overload and contradicts the specification's goal of keeping things "very simple for the user" and "decluttered."

### Cognitive Overload Issues
- **4-tab complexity**: Users must understand "Automatic Matches", "Manual Search", "Custom Value", and "Settings" tabs
- **Decision paralysis**: Equal visual weight given to all options
- **Hidden workflow**: No clear guidance on where to start or what's most important
- **Poor information hierarchy**: Advanced settings equally prominent as primary actions

### User Experience Problems  
- **Too many clicks**: Simple reconciliation requires multiple navigation steps
- **Unclear terminology**: "QID", "wikibase-item" instead of user-friendly "Wikidata item"
- **Inefficient workflows**: High-confidence matches still require multiple confirmations
- **Redundant buttons**: Continue button unnecessary when user has already selected a value

### Core Design Philosophy
1. **Smart defaults**: Show most relevant content first based on match confidence
2. **Progressive disclosure**: Reveal additional options only when needed  
3. **Context-aware interface**: Adapt based on property type and available matches
4. **Auto-progression**: Streamline workflows by eliminating unnecessary confirmation steps

### New Modal Structure

```
┌─────────────────────────────────────────────────────────┐
│ HEADER                                                  │
│ Reconcile: [Property Name]                              │
│ Value: "[Original Value]" from [Item Context]          │
│ Expected: Wikidata item                                 │
├─────────────────────────────────────────────────────────┤
│ PRIMARY RECOMMENDATIONS                                 │
│ ┌─────────────────────────────────────────────────────┐ │
│ │ HIGH CONFIDENCE MATCHES (≥80%)                      │ │
│ │ ┌─────────────────┐ ┌─────────────────┐             │ │
│ │ │ 🎯 Best Match   │ │ 🎯 Alt Match    │             │ │
│ │ │ 95% confidence  │ │ 85% confidence  │             │ │
│ │ │ [Select]        │ │ [Select]        │             │ │
│ │ └─────────────────┘ └─────────────────┘             │ │
│ │ ▼ Scroll for more high-confidence matches           │ │
│ └─────────────────────────────────────────────────────┘ │
│                                                         │
│ FALLBACK OPTIONS (for low/no confidence)               │
│ ┌─────────────────────────────────────────────────────┐ │
│ │ 🔍 Search Wikidata: [_______________] [Search]      │ │
│ │ ➕ Create New Wikidata Item                         │ │
│ └─────────────────────────────────────────────────────┘ │
│                                                         │
│ PROGRESSIVE DISCLOSURE                                  │
│ [▼ More Options] (expandable)                          │
│ └─ Manual search, property type override, etc.         │
├─────────────────────────────────────────────────────────┤
│ ACTIONS                                                 │
│ [Skip for Later]  [⚙️ Auto-advance: ON/OFF]           │
└─────────────────────────────────────────────────────────┘
```

#### High Confidence Scenario (≥80% matches)
- **Show all matches ≥80%** in a horizontally scrollable container
- **No "Create New Item" button** (high confidence means good matches exist)
- **Immediate selection**: Clicking a match automatically accepts it
- **Auto-advance option**: Configurable setting to move to next reconciliation automatically

#### Medium Confidence Scenario (60-79% matches)
- **Show best matches** but with "More Options" section expanded by default
- **Include "Create New Item"** as fallback option
- **Manual search** prominently available

#### Low/No Confidence Scenario (<60% or no matches)
- **Prioritize manual search** with prominent search box
- **"Create New Item" button** clearly visible
- **Original value pre-filled** in search box

#### Non-Wikidata Properties
- **Skip reconciliation entirely** and show appropriate input field
- **No search or create options** (not applicable)

#### Dynamic Button Behavior
- **Remove "Confirm" button**: Selecting a match auto-confirms and advances
- **Keep "Skip for Later"**: Always available for any reconciliation type
- **Context-aware "Create New"**: 
  - Only shown for Wikidata item properties
  - Only when matches are poor quality (<80% confidence)
  - Opens Wikidata's Special:NewItem in new tab

#### Auto-Advancement Feature
- **User preference toggle**: "Auto-advance to next reconciliation"
- **Smart progression**: After selection, automatically open next pending cell
- **Respect user choice**: Allow disabling auto-advance for careful review workflows

#### User-Friendly Language
- **"Wikidata item"** instead of "QID", "wikibase-item", or "Q-ID"
- **"Expected: Wikidata item"** clearly shown in header
- **Confidence percentages** instead of technical scores
- **"Search Wikidata"** instead of "Manual Search"

#### Primary Layer (Always Visible)
- Best automatic matches for Wikidata items
- Appropriate input field for non-Wikidata properties
- Clear indication of expected value type

#### Secondary Layer (Expandable)
- Alternative reconciliation approaches
- Property type override controls
- Advanced search options
- Help and context information

#### File: `src/js/steps/reconciliation.js`

1. **Replace `createReconciliationModalContent()` function**
   ```javascript
   function createReconciliationModalContent(itemId, property, valueIndex, value) {
       const propertyType = detectPropertyType(property);
       const inputConfig = getInputFieldConfig(propertyType);
       
       return `
           <div class="reconciliation-modal-v2">
               <div class="reconciliation-header">
                   <h4>Reconcile: ${property}</h4>
                   <p class="original-value">Value: <strong>"${value}"</strong></p>
                   <p class="item-context">From: ${getItemTitle(itemId)}</p>
                   <p class="expected-type">Expected: ${getUserFriendlyTypeName(propertyType)}</p>
               </div>
               
               <div class="primary-recommendations">
                   <div class="loading-state">Finding matches...</div>
                   <div class="high-confidence-matches" style="display: none;"></div>
                   <div class="fallback-options" style="display: none;"></div>
               </div>
               
               <div class="progressive-disclosure">
                   <button class="expand-options" onclick="toggleMoreOptions()">
                       ▼ More Options
                   </button>
                   <div class="expanded-options" style="display: none;"></div>
               </div>
               
               <div class="reconciliation-actions">
                   <button class="btn secondary" onclick="skipReconciliation()">Skip for Later</button>
                   <div class="auto-advance-toggle">
                       <label>
                           <input type="checkbox" id="auto-advance" ${getAutoAdvanceSetting() ? 'checked' : ''}>
                           Auto-advance to next
                       </label>
                   </div>
               </div>
           </div>
       `;
   }
   ```

2. **Implement `displaySmartRecommendations()` function**
   ```javascript
   async function displaySmartRecommendations(matches, propertyType, value) {
       const loadingState = document.querySelector('.loading-state');
       const highConfidenceContainer = document.querySelector('.high-confidence-matches');
       const fallbackContainer = document.querySelector('.fallback-options');
       
       loadingState.style.display = 'none';
       
       if (propertyType \!== 'wikibase-item') {
           // Non-Wikidata properties: show custom input directly
           showCustomInputInterface(propertyType, value);
           return;
       }
       
       const highConfidenceMatches = matches.filter(m => m.score >= 80);
       
       if (highConfidenceMatches.length > 0) {
           displayHighConfidenceMatches(highConfidenceMatches);
           highConfidenceContainer.style.display = 'block';
       } else {
           displayFallbackOptions(value, matches);
           fallbackContainer.style.display = 'block';
       }
   }
   ```

3. **Add auto-advancement logic**
   ```javascript
   function selectMatch(matchId, matchLabel) {
       markCellAsReconciled(currentReconciliationCell, {
           type: 'wikidata',
           id: matchId,
           label: matchLabel
       });
       
       modalUI.closeModal();
       
       // Auto-advance if enabled
       if (getAutoAdvanceSetting()) {
           setTimeout(() => {
               reconcileNextUnprocessedCell();
           }, 300); // Brief delay for visual feedback
       }
   }
   ```

#### File: `src/css/style.css`

4. **Remove tab-based styles**
   - Delete `.option-tabs`, `.tab-btn`, `.tab-content` styles
   - Remove tab switching animations

5. **Add progressive disclosure styles**
   ```css
   .reconciliation-modal-v2 {
       max-width: 700px;
       width: 100%;
   }
   
   .primary-recommendations {
       margin-bottom: 1.5rem;
   }
   
   .high-confidence-matches {
       display: flex;
       gap: 1rem;
       overflow-x: auto;
       padding: 1rem;
       background: #f8f9fa;
       border-radius: 8px;
       border: 2px solid var(--success-color);
   }
   
   .confidence-match-card {
       min-width: 250px;
       padding: 1rem;
       background: white;
       border-radius: 6px;
       border: 1px solid #dee2e6;
       cursor: pointer;
       transition: all 0.2s ease;
   }
   
   .confidence-match-card:hover {
       border-color: var(--primary-color);
       transform: translateY(-2px);
       box-shadow: 0 4px 12px rgba(0,0,0,0.1);
   }
   
   .match-confidence {
       color: var(--success-color);
       font-weight: bold;
       font-size: 0.9rem;
   }
   
   .fallback-options {
       padding: 1.5rem;
       background: #fff3cd;
       border-radius: 8px;
       border: 1px solid #ffeaa7;
   }
   
   .search-wikidata {
       display: flex;
       gap: 0.5rem;
       margin-bottom: 1rem;
   }
   
   .search-wikidata input {
       flex: 1;
       padding: 0.75rem;
       border: 1px solid #dee2e6;
       border-radius: 4px;
   }
   
   .create-new-item {
       padding: 0.75rem 1rem;
       background: var(--primary-color);
       color: white;
       border: none;
       border-radius: 4px;
       cursor: pointer;
       font-weight: 500;
   }
   
   .progressive-disclosure {
       margin-bottom: 1rem;
   }
   
   .expand-options {
       width: 100%;
       padding: 0.75rem;
       background: #f8f9fa;
       border: 1px solid #dee2e6;
       border-radius: 4px;
       cursor: pointer;
       text-align: left;
   }
   
   .auto-advance-toggle {
       display: flex;
       align-items: center;
       gap: 0.5rem;
   }
   ```

### Phase 2: Smart Behavior Implementation (Week 3)

1. **Confidence-based content switching**
2. **Auto-advancement functionality**
3. **Dynamic button management**
4. **Improved property type detection**

### Phase 3: Enhanced User Experience (Week 4)

1. **User preference persistence**
2. **Keyboard navigation improvements**
3. **Visual feedback and animations**
4. **Comprehensive testing and refinement**

### User Experience Metrics
- [ ] **Reduced clicks**: High-confidence reconciliations complete in 1 click (vs. current 3+ clicks)
- [ ] **Faster workflows**: 60%+ reduction in time for common reconciliation tasks
- [ ] **Lower cognitive load**: Single interface instead of 4-tab navigation
- [ ] **Better success rate**: More users successfully complete reconciliations

### Technical Requirements
- [ ] **All existing functionality preserved**: No feature regression
- [ ] **Backward compatibility**: Existing reconciliation data structures unchanged
- [ ] **Performance improvement**: Faster modal rendering and interaction
- [ ] **Accessibility compliance**: Better keyboard navigation and screen reader support

### Feature Completeness
- [ ] **Smart confidence-based display**: ≥80% matches shown prominently
- [ ] **Auto-advancement option**: User-configurable next-item progression
- [ ] **Dynamic button behavior**: Context-aware action availability
- [ ] **Progressive disclosure**: Advanced options available but not overwhelming
- [ ] **User-friendly terminology**: "Wikidata item" instead of technical terms

### User Testing Scenarios
1. **High-confidence match scenario**: User sees 95% match and accepts with single click
2. **Multiple high-confidence scenario**: User scrolls through several >80% matches
3. **Low-confidence scenario**: User uses manual search to find correct match
4. **No matches scenario**: User creates new Wikidata item
5. **Auto-advancement scenario**: User processes multiple reconciliations efficiently

### Technical Testing
- [ ] **Cross-browser compatibility**: Chrome, Firefox, Safari, Edge
- [ ] **Responsive design**: Works on different screen sizes
- [ ] **Keyboard navigation**: All functions accessible via keyboard
- [ ] **Performance testing**: Modal loads quickly with large match sets
- [ ] **Error handling**: Graceful handling of API failures

### Phase 1: Parallel Implementation
- Implement new modal alongside existing system
- Add feature flag to switch between interfaces
- Extensive testing with existing data

### Phase 2: Gradual Rollout
- Default to new modal for all users
- Monitor for issues and collect feedback
- Provide emergency fallback if needed

### Phase 3: Cleanup
- Remove old modal code and CSS
- Update documentation
- Performance optimizations

## Related Issues/Dependencies

- Integrates with existing reconciliation state management
- Depends on current property type detection system
- Enhances existing auto-reconciliation batch processing
- Maintains compatibility with existing progress tracking

---

**Priority**: High - Core user experience improvement
**Effort**: Medium - Primarily UI/UX restructuring with preserved functionality
**Impact**: High - Dramatically improves reconciliation workflow efficiency
